<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Quiz;
use App\Models\User;
use App\Models\Choice;
use App\Models\Question;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();

    	Quiz::insert([
    		[
    			'name' => 'Showroom EPA',
    			'purpose' => "<p><b>The Purpose of this Performance Appraisal: </b></p><ul><li>Motivate Employee for performance improvement. </li><li>Measure the effectiveness of employee’s competency comparing with the requirement.</li><li>Inform employee about performance management’s principle and development program.</li><li>Implement the fairness principle in evaluating employee’s level of working attainment and effectiveness of competency through open, transparency, two way, interactive communication between employee and direct supervisor.</li><li>Implement active participation of employee and direct supervisor for the evaluation as follows;</li><li>Direct Supervisor: Build and create good atmosphere for motivation enhancement, competency development and performance improvement.</li><li>Employee: Communicate aspiration, self-potentials development, and opportunity to improve performance and competency level. </li></ul>",
    			'instructions' => "<p><b>Instructions:</b></p><ol><li>Place an 'X' in the box under the Rating Scale that most states your evaluation of each stated components.</li><li>Consider the individual's entire performance throughout the year. Don't base your judgment on one or two incidents.</li><li>Space is provided on the last page for comments and explanations.</li></ol>",
    		]
    	]);

        Choice::insert([
            [
                'choice' => 'Exceptional',
                'rating_value' => '5',
                'section' => 'Section 01: Managerial Aspects',
                'definition' => 'The employee consistently exceeds job requirements. Exceptional in all aspects of the stated components. Extraordinary accomplishment or achievement.Outstanding work.',
                'quiz_id' => '1'
            ],
            [
                'choice' => 'Highly Effective',
                'rating_value' => '4',
                'section' => 'Section 01: Managerial Aspects',
                'definition' => 'The employee is highly capable and frequently exceeds expectations in one or more aspects of the stated components. Demonstrates above average ability and initiative.',
                'quiz_id' => '1'
            ],
            [
                'choice' => 'Proficient',
                'rating_value' => '3',
                'section' => 'Section 01: Managerial Aspects',
                'definition' => '',
                'quiz_id' => '1'
            ],
            [
                'choice' => 'Need Improvement',
                'rating_value' => '2',
                'section' => 'Section 01: Managerial Aspects',
                'definition' => 'Performance meets some, but not all requirements of the stated components and Job accomplishments fall short of expectations. Improvement is necessary.',
                'quiz_id' => '1'
            ],
            [
                'choice' => 'Unsatisfactory',
                'rating_value' => '1',
                'section' => 'Section 01: Managerial Aspects',
                'definition' => 'Performance does not meet most aspects of the stated components, also fails to demonstrate sufficient ability and requires regular and ongoing attention. Immediate improvement is required.',
                'quiz_id' => '1'
            ],


            [
                'choice' => 'Exceptional',
                'rating_value' => '5',
                'section' => 'Section 02: Behavioral Skills',
                'definition' => 'The employee consistently exceeds job requirements. Exceptional in all aspects of the stated components. Extraordinary accomplishment or achievement.Outstanding work.',
                'quiz_id' => '1'
            ],
            [
                'choice' => 'Highly Effective',
                'rating_value' => '4',
                'section' => 'Section 02: Behavioral Skills',
                'definition' => 'The employee is highly capable and frequently exceeds expectations in one or more aspects of the stated components. Demonstrates above average ability and initiative.',
                'quiz_id' => '1'
            ],
            [
                'choice' => 'Proficient',
                'rating_value' => '3',
                'section' => 'Section 02: Behavioral Skills',
                'definition' => '',
                'quiz_id' => '1'
            ],
            [
                'choice' => 'Need Improvement',
                'rating_value' => '2',
                'section' => 'Section 02: Behavioral Skills',
                'definition' => 'Performance meets some, but not all requirements of the stated components and Job accomplishments fall short of expectations. Improvement is necessary.',
                'quiz_id' => '1'
            ],
            [
                'choice' => 'Unsatisfactory',
                'rating_value' => '1',
                'section' => 'Section 02: Behavioral Skills',
                'definition' => 'Performance does not meet most aspects of the stated components, also fails to demonstrate sufficient ability and requires regular and ongoing attention. Immediate improvement is required.',
                'quiz_id' => '1'
            ],
        ]);

        Question::insert([
        	[
        		'question' => 'Displays in-depth understanding of job',
        		'category' => 'Job Knowledge',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Has sufficient knowledge of processes and policies of business operations to make informed decisions within the scope of responsibility',
        		'category' => 'Job Knowledge',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Keeps up to date with best practices and new developments',
        		'category' => 'Job Knowledge',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Uses and share the job knowledge to mentor other employees',
        		'category' => 'Job Knowledge',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Exhibits ability to learn and apply new skills related to the job',
        		'category' => 'Job Knowledge',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],


        	[
        		'question' => 'Exhibits ability to learn and apply new skills related to the job',
        		'category' => 'Customer Service And Sales',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Takes initiative to inquire about customer needs, feedback and opinions',
        		'category' => 'Customer Service And Sales',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Encourages and develops customer service skills in employees',
        		'category' => 'Customer Service And Sales',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Actively involved in sales related activities',
        		'category' => 'Customer Service And Sales',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Effectively handles and responds to customer requests and complaints',
        		'category' => 'Customer Service And Sales',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],

        	[
        		'question' => 'Motivates others; creates enthusiasm for team effort',
        		'category' => 'Communication',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Sets a model for teamwork that encourages common goals',
        		'category' => 'Communication',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Is an effective team builder promoting strong working relationships',
        		'category' => 'Communication',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Interacts effectively with supervisor',
        		'category' => 'Communication',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Sets a positive example for the team',
        		'category' => 'Communication',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],

        	[
        		'question' => 'Motivates others; creates enthusiasm for team effort',
        		'category' => 'Cooperation/Teamwork',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Sets a model for teamwork that encourages common goals',
        		'category' => 'Cooperation/Teamwork',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Is an effective team builder promoting strong working relationships',
        		'category' => 'Cooperation/Teamwork',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Interacts effectively with supervisor',
        		'category' => 'Cooperation/Teamwork',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Sets a positive example for the team',
        		'category' => 'Cooperation/Teamwork',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],

        	[
        		'question' => 'Gathers and analyzes information skillfully',
        		'category' => 'Planning, Problem Solving & Organizing',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Able to prioritize work. Sets realistic deadlines for self and ensures deadlines are met',
        		'category' => 'Planning, Problem Solving & Organizing',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Open to new ideas, allows and supports employees to make decisions',
        		'category' => 'Planning, Problem Solving & Organizing',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Integrates changes smoothly',
        		'category' => 'Planning, Problem Solving & Organizing',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Works well in group problem-solving situations',
        		'category' => 'Planning, Problem Solving & Organizing',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],

        	[
        		'question' => 'Positive attitude with colleagues and supervisors',
        		'category' => 'Attitude and Discipline',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Adhering to organization policies, rules and regulations',
        		'category' => 'Attitude and Discipline',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Good attendance & punctuality / unplanned leave & frequent absence',
        		'category' => 'Attitude and Discipline',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Adherence to dress code and attire ',
        		'category' => 'Attitude and Discipline',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Applies negotiation skills to gain support for even the most controversial issues',
        		'category' => 'Attitude and Discipline',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],

        	[
        		'question' => 'Work is accurate and precise.',
        		'category' => 'Performance and Productivity',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Strives to increase productivity.',
        		'category' => 'Performance and Productivity',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Displays original thinking, innovative approaches and ideas creativity',
        		'category' => 'Performance and Productivity',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Applies feedback to improve performance',
        		'category' => 'Performance and Productivity',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Looks for ways to improve and promote quality of work',
        		'category' => 'Performance and Productivity',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],

        	[
        		'question' => 'Displays in-depth understanding of product features, trends and usages',
        		'category' => 'Product Knowledge and Inventory Control',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Ability to identify the product and market gaps',
        		'category' => 'Product Knowledge and Inventory Control',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Control damage products and maintain up to date inventory',
        		'category' => 'Product Knowledge and Inventory Control',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Sets effective control on inventory & stock levels',
        		'category' => 'Product Knowledge and Inventory Control',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Assuring the availability of all basic products ',
        		'category' => 'Product Knowledge and Inventory Control',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],

        	[
        		'question' => 'Self-Motivated in Completing Assignments',
        		'category' => 'Ownership & Initiative',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Makes Suggestions to Improve Performance or Productivity.',
        		'category' => 'Ownership & Initiative',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Seeks out New Assignments and Assumes Additional Duties as needed',
        		'category' => 'Ownership & Initiative',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Takes Independent Actions and Calculated Risks',
        		'category' => 'Ownership & Initiative',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Undertakes Self-Development Activities',
        		'category' => 'Ownership & Initiative',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],

        	[
        		'question' => 'Reliable in Completing Assigned Tasks',
        		'category' => 'Dependability',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Follows Instructions; Stays on Task Without Constant Supervision',
        		'category' => 'Dependability',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Ability to Handle Multiple Demands Or Multi-Task',
        		'category' => 'Dependability',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
        	[
        		'question' => 'Takes responsibility for own actions',
        		'category' => 'Dependability',
        		'section' => 'Section 01: Managerial Aspects',
        		'type' => '1',
        		'quiz_id' => '1',
        	],
            [
                'question' => 'Commitment Towards Doing Best Job Possible',
                'category' => 'Dependability',
                'section' => 'Section 01: Managerial Aspects',
                'type' => '1',
                'quiz_id' => '1',
            ],

            [
                'question' => 'Resistance To Pressure',
                'category' => 'N/A',
                'section' => 'Section 02: Behavioral Skills',
                'type' => '1',
                'quiz_id' => '1',
            ],
            [
                'question' => 'Flexibility & Change Agent',
                'category' => 'N/A',
                'section' => 'Section 02: Behavioral Skills',
                'type' => '1',
                'quiz_id' => '1',
            ],
            [
                'question' => 'Innovative & Creative',
                'category' => 'N/A',
                'section' => 'Section 02: Behavioral Skills',
                'type' => '1',
                'quiz_id' => '1',
            ],
            [
                'question' => 'Professional Development',
                'category' => 'N/A',
                'section' => 'Section 02: Behavioral Skills',
                'type' => '1',
                'quiz_id' => '1',
            ],
            [
                'question' => 'Results Oriented',
                'category' => 'N/A',
                'section' => 'Section 02: Behavioral Skills',
                'type' => '1',
                'quiz_id' => '1',
            ],
            [
                'question' => 'Personal Development',
                'category' => 'N/A',
                'section' => 'Section 02: Behavioral Skills',
                'type' => '1',
                'quiz_id' => '1',
            ],
            [
                'question' => 'Passionate',
                'category' => 'N/A',
                'section' => 'Section 02: Behavioral Skills',
                'type' => '1',
                'quiz_id' => '1',
            ],
            [
                'question' => 'Influencer',
                'category' => 'N/A',
                'section' => 'Section 02: Behavioral Skills',
                'type' => '1',
                'quiz_id' => '1',
            ],
            [
                'question' => 'Empathy',
                'category' => 'N/A',
                'section' => 'Section 02: Behavioral Skills',
                'type' => '1',
                'quiz_id' => '1',
            ],
            [
                'question' => 'Self Esteem',
                'category' => 'N/A',
                'section' => 'Section 02: Behavioral Skills',
                'type' => '1',
                'quiz_id' => '1',
            ],
        ]);

        User::insert([
            [
                'email' => '000610@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '000610',
                'name' => 'Mohamed Zarook Mohamed Anas',
                'department' => 'Wellawatte',
                'designation' => 'Senior Manager - Showroom',
            ],
            [
                'email' => '001922@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '001922',
                'name' => 'Mohamed Musthafa Satham Hussain',
                'department' => 'Wellawatte',
                'designation' => 'Assistant Manager - Showroom',
            ],
            [
                'email' => '003456@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '003456',
                'name' => 'Kumara Waduge Sharmila Chathurangani',
                'department' => 'Wellawatte',
                'designation' => 'Floor Supervisor',
            ],
            [
                'email' => '003616@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '003616',
                'name' => 'Mohamed Farook Mohamed Nijam',
                'department' => 'Wellawatte',
                'designation' => 'Management Trainee 11',
            ],
            [
                'email' => '005403@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '005403',
                'name' => 'Mohamed Siyad Mohamed Rislan',
                'department' => 'Wellawatte',
                'designation' => 'Management Trainee 11',
            ],
            [
                'email' => '005633@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '005633',
                'name' => 'Habeebu Rahuman Mohammed Musammil',
                'department' => 'Wellawatte',
                'designation' => 'Management Trainee 11',
            ],
            [
                'email' => '006024@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '006024',
                'name' => 'Mohamed Hafeel Hasmathulla',
                'department' => 'Wellawatte',
                'designation' => 'Floor Supervisor',
            ],
            [
                'email' => '006452@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '006452',
                'name' => 'Mohamed Waseem Juranpathi',
                'department' => 'Wellawatte',
                'designation' => 'Customer Relations Officer',
            ],
            [
                'email' => '007342@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '007342',
                'name' => 'Subramaniyam Suresh Kumar',
                'department' => 'Wellawatte',
                'designation' => 'Senior Team Leader',
            ],
            [
                'email' => '007395@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '007395',
                'name' => 'Mohamed Naleer Mohamed Riyal',
                'department' => 'Wellawatte',
                'designation' => 'Customer Relations Officer',
            ],
            [
                'email' => '007637@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '007637',
                'name' => 'Paththiyanathan Stellan',
                'department' => 'Wellawatte',
                'designation' => 'Sales Personnel-Senior',
            ],
            [
                'email' => '007649@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '007649',
                'name' => 'Mohamed Sahabdeen Mohamed',
                'department' => 'Wellawatte',
                'designation' => 'Team Leader',
            ],
            [
                'email' => '007729@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '007729',
                'name' => 'Mohamed Fazil Faraj',
                'department' => 'Wellawatte',
                'designation' => 'Team Leader',
            ],
            [
                'email' => '007929@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '007929',
                'name' => 'Mohamed Faizal Inamul Hassan',
                'department' => 'Wellawatte',
                'designation' => 'Sales Personnel-Senior',
            ],
            [
                'email' => '007930@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '007930',
                'name' => 'Thiyogu Dilani',
                'department' => 'Wellawatte',
                'designation' => 'Sales Personnel-Senior',
            ],
            [
                'email' => '008039@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008039',
                'name' => 'Gnanasekaran Thanushka',
                'department' => 'Wellawatte',
                'designation' => 'Team Leader',
            ],
            [
                'email' => '008069@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008069',
                'name' => 'Abdul Razak Mohamed Inshah',
                'department' => 'Wellawatte',
                'designation' => 'Sales Personnel-Senior',
            ],
            [
                'email' => '008182@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008182',
                'name' => 'Hamza Mohammadu Ashik',
                'department' => 'Wellawatte',
                'designation' => 'Cashier-Senior',
            ],
            [
                'email' => '008209@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008209',
                'name' => 'Sathiyaseelan Nanthini',
                'department' => 'Wellawatte',
                'designation' => 'Sales Personnel-Senior',
            ],
            [
                'email' => '008279@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008279',
                'name' => 'Marimuthu Anthony Lowrance',
                'department' => 'Wellawatte',
                'designation' => 'Team Leader',
            ],
            [
                'email' => '008338@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008338',
                'name' => 'Muhammadu Ranees Muhammadu Rafhan',
                'department' => 'Wellawatte',
                'designation' => 'Sales Personnel',
            ],
            [
                'email' => '008348@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008348',
                'name' => 'Abdul Saththar Mohammadu Rifawus',
                'department' => 'Wellawatte',
                'designation' => 'Cashier',
            ],
            [
                'email' => '008350@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008350',
                'name' => 'Ajmeer Muhammadu Shafras',
                'department' => 'Wellawatte',
                'designation' => 'Trainee Team Member-VM',
            ],
            [
                'email' => '008462@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008462',
                'name' => 'Farook Mohamed Niyas',
                'department' => 'Wellawatte',
                'designation' => 'Cook',
            ],
            [
                'email' => '008951@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008951',
                'name' => 'Lafeer Fathima Ramza',
                'department' => 'Wellawatte',
                'designation' => 'Customer Relations Officer',
            ],
            [
                'email' => '009055@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009055',
                'name' => 'Mohamed Raufdeen Mohamed Ashfaak',
                'department' => 'Wellawatte',
                'designation' => 'Customer Relations Officer',
            ],
            [
                'email' => '009120@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009120',
                'name' => 'Mohammed Shahim Mohammed Abdulla',
                'department' => 'Wellawatte',
                'designation' => 'Trainee Team Member-VM',
            ],
            [
                'email' => '009122@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009122',
                'name' => 'Habeebu Rahman Mujeeb Ahamed',
                'department' => 'Wellawatte',
                'designation' => 'Sales Personnel',
            ],
            [
                'email' => '009586@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009586',
                'name' => 'Vithanage Shiranthi Chandrika',
                'department' => 'Wellawatte',
                'designation' => 'Sales Personnel-Trainee',
            ],
            [
                'email' => '009774@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009774',
                'name' => 'Abdul Razik Ahamed Yoosuf',
                'department' => 'Wellawatte',
                'designation' => 'Sales Personnel-Trainee',
            ],
            [
                'email' => '009813@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009813',
                'name' => 'Nihas Sheedh',
                'department' => 'Wellawatte',
                'designation' => 'Sales Personnel-Trainee',
            ],
            [
                'email' => '009893@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009893',
                'name' => 'Ganeshkumar Priya',
                'department' => 'Wellawatte',
                'designation' => 'Sales Personnel-Trainee',
            ],
            [
                'email' => '010042@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010042',
                'name' => 'Murugaiya Dhanalaxmi',
                'department' => 'Wellawatte',
                'designation' => 'Sales Personnel',
            ],
            [
                'email' => '010115@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010115',
                'name' => 'Muhamed Faizar Isthak Ahamed',
                'department' => 'Wellawatte',
                'designation' => 'Cashier-Trainee',
            ],
            [
                'email' => '010193@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010193',
                'name' => 'Sivakumar Vinojini',
                'department' => 'Wellawatte',
                'designation' => 'Sales Personnel-Trainee',
            ],
            [
                'email' => '010194@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010194',
                'name' => 'Mammadu Milabdeen Razeena',
                'department' => 'Wellawatte',
                'designation' => 'Sales Personnel-Trainee',
            ],
            [
                'email' => '010195@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010195',
                'name' => 'Sajeera Noordeen',
                'department' => 'Wellawatte',
                'designation' => 'Fit-On-Security',
            ],
            [
                'email' => '010196@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010196',
                'name' => 'Mahaboob Aadhil Akram',
                'department' => 'Wellawatte',
                'designation' => 'Sales Personnel-Trainee',
            ],
            [
                'email' => '010302@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010302',
                'name' => 'Abdul Fayid Mohomad Sahran',
                'department' => 'Wellawatte',
                'designation' => 'Sales Personnel-Trainee',
            ],
            [
                'email' => '010303@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010303',
                'name' => 'Saad Bin Sadiq',
                'department' => 'Wellawatte',
                'designation' => 'Cashier-Trainee',
            ],
            [
                'email' => '000173@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '000173',
                'name' => 'Nanayakkara Agarage Sampath Lalani',
                'department' => 'Accounts',
                'designation' => 'Accountant',
            ],
            [
                'email' => '000759@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '000759',
                'name' => 'Ahamed Azmi Azeez',
                'department' => 'Accounts',
                'designation' => 'Manager - Finance',
            ],
            [
                'email' => '000918@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '000918',
                'name' => 'Abdul Hameed Mohamed Zaheem',
                'department' => 'Accounts',
                'designation' => 'Senior Chief Cashier',
            ],
            [
                'email' => '003155@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '003155',
                'name' => 'Mohamedu Riyal Mohamed Rifas',
                'department' => 'Accounts',
                'designation' => 'Chief Cashier',
            ],
            [
                'email' => '003200@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '003200',
                'name' => 'Abdul Azeez Mohamed Al Irsadh',
                'department' => 'Accounts',
                'designation' => 'Assistant Accountant',
            ],
            [
                'email' => '003737@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '003737',
                'name' => 'Mohamed Hussain Siththi Jaseema',
                'department' => 'Accounts',
                'designation' => 'Junior Executive – Accounts',
            ],
            [
                'email' => '004436@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '004436',
                'name' => 'Yoosuf Ismail Yoosuf Ahamed',
                'department' => 'Accounts',
                'designation' => 'Executive - Accounts',
            ],
            [
                'email' => '006058@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '006058',
                'name' => 'Mazhar Hameed Fathima Nasooha',
                'department' => 'Accounts',
                'designation' => 'Assistant Finance Manager',
            ],
            [
                'email' => '008592@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008592',
                'name' => 'Noorullah Muhammadh Sajidh',
                'department' => 'Accounts',
                'designation' => 'Junior Executive – Accounts',
            ],
            [
                'email' => '009513@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009513',
                'name' => 'Mohomed Fazee Mohomed Fayas',
                'department' => 'Accounts',
                'designation' => 'Junior Executive – Accounts',
            ],
            [
                'email' => '009663@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009663',
                'name' => 'Hasan Hidayathullah Ruzan Ahmed',
                'department' => 'Accounts',
                'designation' => 'Accounts Assistant',
            ],
            [
                'email' => '009751@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009751',
                'name' => 'Fathima Afrah Rizvi',
                'department' => 'Accounts',
                'designation' => 'Junior Executive – Accounts',
            ],
            [
                'email' => '010402@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010402',
                'name' => 'Mohamed Thahir Aaqeel Ahamath',
                'department' => 'Accounts',
                'designation' => 'Executive - Accounts',
            ],
            [
                'email' => '000001@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '000001',
                'name' => 'Noohu Lebbe Jaufer',
                'department' => 'Administration',
                'designation' => 'Manager-Field Operations',
            ],
            [
                'email' => '000013@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '000013',
                'name' => 'Mohamed Raziek Mohamed Ashraff',
                'department' => 'Administration',
                'designation' => 'Senior Operations Manager',
            ],
            [
                'email' => '000033@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '000033',
                'name' => 'Abdul Samad Mohamed Sihaan',
                'department' => 'Administration',
                'designation' => 'Assistant Manager - Product Audit',
            ],
            [
                'email' => '000100@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '000100',
                'name' => 'Mohamed Hanifa Mohamed Jawfer',
                'department' => 'Administration',
                'designation' => 'Senior Operations Manager',
            ],
            [
                'email' => '000101@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '000101',
                'name' => 'Abdul Hassan Amjad',
                'department' => 'Administration',
                'designation' => 'General Manager',
            ],
            [
                'email' => '000111@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '000111',
                'name' => 'Mohamed Haniffa Ahmed Hanafi',
                'department' => 'Administration',
                'designation' => 'Asst. General Manager',
            ],
            [
                'email' => '000418@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '000418',
                'name' => 'Lafeer Mohamed Naleem',
                'department' => 'Administration',
                'designation' => 'Senior Area Manager',
            ],
            [
                'email' => '000467@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '000467',
                'name' => 'Noohu Lebbe Anver Mackey',
                'department' => 'Administration',
                'designation' => 'Senior Operations Manager',
            ],
            [
                'email' => '000577@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '000577',
                'name' => 'Mohammadu Fulail Mohammadu Nihaj',
                'department' => 'Administration',
                'designation' => 'Accomadation Officer',
            ],
            [
                'email' => '000584@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '000584',
                'name' => 'Mohamed Ibrahim Mohamed Razeem',
                'department' => 'Administration',
                'designation' => 'Junior Area Manager',
            ],
            [
                'email' => '001014@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '001014',
                'name' => 'Mohamed Sahel Mohamed Shamayil',
                'department' => 'Administration',
                'designation' => 'Senior Area Manager',
            ],
            [
                'email' => '001887@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '001887',
                'name' => 'Sikkandar Mohammed Risvi',
                'department' => 'Administration',
                'designation' => 'Junior Area Manager',
            ],
            [
                'email' => '002659@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '002659',
                'name' => 'Abdul Cader Najumudeen',
                'department' => 'Administration',
                'designation' => 'Secretary - Admin',
            ],
            [
                'email' => '005135@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '005135',
                'name' => 'Mohamed Nisam Mohamed Imran',
                'department' => 'Administration',
                'designation' => 'Senior Area Manager',
            ],
            [
                'email' => '008925@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008925',
                'name' => 'Mohomed Maharoof Mohomed Masharick',
                'department' => 'Administration',
                'designation' => 'Operations Manager',
            ],
            [
                'email' => '009654@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009654',
                'name' => 'Gnei Nazly Askin',
                'department' => 'Administration',
                'designation' => 'Executive Secretary',
            ],
            [
                'email' => '009999@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009999',
                'name' => 'Mohideen Abdul Cader Mohamed Abbrar  Ahamed',
                'department' => 'Administration',
                'designation' => 'Operations Manager',
            ],
            [
                'email' => '010141@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010141',
                'name' => 'Firaz Dylan Kareem',
                'department' => 'Administration',
                'designation' => 'Executive - Food & Services',
            ],
            [
                'email' => '010142@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010142',
                'name' => 'Shihara Azali Sudar',
                'department' => 'Administration',
                'designation' => 'Personal Assistant',
            ],
            [
                'email' => '007091@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '007091',
                'name' => 'Mohamed Nalmi Rimas  Ahamed',
                'department' => 'Audit',
                'designation' => 'Senior Executive-Internal Audit',
            ],
            [
                'email' => '008656@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008656',
                'name' => 'Ahamed Yakeen Azma',
                'department' => 'Audit',
                'designation' => 'Executive-Audit',
            ],
            [
                'email' => '009208@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009208',
                'name' => 'Abdul Fareed Riyas Mohammed',
                'department' => 'Audit',
                'designation' => 'Audit Assistant',
            ],
            [
                'email' => '009518@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009518',
                'name' => 'Ameer Ali  Abdun Nafih',
                'department' => 'Audit',
                'designation' => 'Manager-Internal Audit',
            ],
            [
                'email' => '009793@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009793',
                'name' => 'Abdul Laththeef Abdullah Suraij',
                'department' => 'Audit',
                'designation' => 'Audit Assistant',
            ],
            [
                'email' => '010077@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010077',
                'name' => 'Mohamed Niyas Mohamed Siras',
                'department' => 'Audit',
                'designation' => 'Audit Assistant',
            ],
            [
                'email' => '000515@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '000515',
                'name' => 'Mohamed Musthapa Anwar',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Assistant Manager - Showroom',
            ],
            [
                'email' => '003047@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '003047',
                'name' => 'Mohammed Muniwar Mohammed Aslam',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Management Trainee-I',
            ],
            [
                'email' => '003562@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '003562',
                'name' => 'Mohamed Jabir Shafras',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Management Trainee-I',
            ],
            [
                'email' => '004115@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '004115',
                'name' => 'Liyana Pathiranage Hiroshi Wasula Harshani Costa',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Senior Team Leader',
            ],
            [
                'email' => '004754@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '004754',
                'name' => 'Sinha Arachchillage Renuka Indrani  Menike',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Senior Team Leader',
            ],
            [
                'email' => '005936@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '005936',
                'name' => 'Abdul Jabbar Mohamed  Yasar',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Senior Team Leader',
            ],
            [
                'email' => '006169@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '006169',
                'name' => 'Buhar Mohomed Anush Buhar',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Cashier-Senior',
            ],
            [
                'email' => '006413@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '006413',
                'name' => 'Mahakandura Mahanamage Nisansala Priyadarshani',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Senior CRO',
            ],
            [
                'email' => '006669@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '006669',
                'name' => 'Muhammadu Faris Muhammadu  Farhath',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Senior Team Leader',
            ],
            [
                'email' => '006762@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '006762',
                'name' => 'Yesumani  Agostas',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Floor Supervisor',
            ],
            [
                'email' => '007837@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '007837',
                'name' => 'Senanayaka Herath Mudiyanselage Dilani Chathusika Senanayaka',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Team Leader',
            ],
            [
                'email' => '008256@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008256',
                'name' => 'Korawage Hasangika Maduwanthi',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Customer Relations Officer',
            ],
            [
                'email' => '008304@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008304',
                'name' => 'Noransahalu Dilani',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Customer Relations Officer',
            ],
            [
                'email' => '008587@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008587',
                'name' => 'Mohamed Baseer Sihan',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Trainee Team Member-VM',
            ],
            [
                'email' => '008803@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008803',
                'name' => 'Pathmanathan Kamalasani',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Sales Personnel-Senior',
            ],
            [
                'email' => '009297@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009297',
                'name' => 'Mohommadhu Abdul Wahab Mohommadhu Waseem',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Sales Personnel',
            ],
            [
                'email' => '009298@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009298',
                'name' => 'Faris Mohamed Farsath',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Sales Personnel',
            ],
            [
                'email' => '009392@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009392',
                'name' => 'Muhammadu Farook Muhammadu Niyas',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Sales Personnel',
            ],
            [
                'email' => '009448@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009448',
                'name' => 'Alagiya Hewage Dayani',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Cashier',
            ],
            [
                'email' => '009449@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009449',
                'name' => 'Mohomed Mubarak Mohamed Aski',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Sales Personnel',
            ],
            [
                'email' => '009496@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009496',
                'name' => 'Riyaldeen Fathuma Yusriya',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Sales Personnel',
            ],
            [
                'email' => '009709@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009709',
                'name' => 'Noorul Huda Mohamed Nushan',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Cashier-Trainee',
            ],
            [
                'email' => '009759@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009759',
                'name' => 'Abdul Munaf Haseem Mohomed',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Sales Personnel',
            ],
            [
                'email' => '009797@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009797',
                'name' => 'Egoda Rajage Panchali Gayangani',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Sales Personnel',
            ],
            [
                'email' => '009798@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009798',
                'name' => 'Muhammadu Baseer Mohommed Rasid',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Sales Personnel',
            ],
            [
                'email' => '009843@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009843',
                'name' => 'Muhammadu Nawsad Isaq Ahamed',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Trainee Team Member-VM',
            ],
            [
                'email' => '010336@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010336',
                'name' => 'Kalaivany Mohamad Riyas',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Fit-On-Security',
            ],
            [
                'email' => '010407@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010407',
                'name' => 'Pathiranage Radha Lakmali Perera',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Sales Personnel',
            ],
            [
                'email' => '010462@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010462',
                'name' => 'Sathiswaran Seshathri',
                'department' => 'Dehiwala Ladies',
                'designation' => 'Sales Personnel-Trainee',
            ],
            [
                'email' => '000463@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '000463',
                'name' => 'Mohamed Althaaf Khan',
                'department' => 'Hyde Park',
                'designation' => 'Assistant Manager - Showroom',
            ],
            [
                'email' => '002102@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '002102',
                'name' => 'Mohamed Mohamed Rilwan',
                'department' => 'Hyde Park',
                'designation' => 'Management Trainee-I',
            ],
            [
                'email' => '004012@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '004012',
                'name' => 'Ravindra Kumar Gunasekara',
                'department' => 'Hyde Park',
                'designation' => 'Assistant Manager - Showroom',
            ],
            [
                'email' => '004087@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '004087',
                'name' => 'Mohamed Niyas Mohamed',
                'department' => 'Hyde Park',
                'designation' => 'Security Personnel',
            ],
            [
                'email' => '005520@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '005520',
                'name' => 'Vithana Arachchige Nadeesha Sandamali',
                'department' => 'Hyde Park',
                'designation' => 'Senior Team Leader',
            ],
            [
                'email' => '005522@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '005522',
                'name' => 'Iqbal Muhammad Roomiy',
                'department' => 'Hyde Park',
                'designation' => 'Management Trainee 11',
            ],
            [
                'email' => '005807@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '005807',
                'name' => 'Liyanawaduge Thilini Geethanjali',
                'department' => 'Hyde Park',
                'designation' => 'Senior Team Leader',
            ],
            [
                'email' => '005894@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '005894',
                'name' => 'Arumugam Vaineswaran',
                'department' => 'Hyde Park',
                'designation' => 'Cashier-Senior',
            ],
            [
                'email' => '005909@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '005909',
                'name' => 'Opatha Kankanamalage Dinoshika Priyadarshani Nandasiri',
                'department' => 'Hyde Park',
                'designation' => 'Senior CRO',
            ],
            [
                'email' => '005919@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '005919',
                'name' => 'Mohamed Sarook Mohamed Safan',
                'department' => 'Hyde Park',
                'designation' => 'Management Trainee 11',
            ],
            [
                'email' => '006350@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '006350',
                'name' => 'Allapichchai Abdul Rafeek',
                'department' => 'Hyde Park',
                'designation' => 'Cook',
            ],
            [
                'email' => '007028@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '007028',
                'name' => 'Jasin Arachchige Madushi Samudrika',
                'department' => 'Hyde Park',
                'designation' => 'Senior Team Leader',
            ],
            [
                'email' => '007277@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '007277',
                'name' => 'Muhammadu Muzammil Muhammadu Safa',
                'department' => 'Hyde Park',
                'designation' => 'Team Member - Visual Merchandizing',
            ],
            [
                'email' => '007419@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '007419',
                'name' => 'Mohammadu Subair Mohammadu Azeem',
                'department' => 'Hyde Park',
                'designation' => 'Team Leader',
            ],
            [
                'email' => '008081@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008081',
                'name' => 'Ramdas Subashini',
                'department' => 'Hyde Park',
                'designation' => 'Customer Relations Officer',
            ],
            [
                'email' => '008597@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008597',
                'name' => 'Jayasekara Pathirana Sujith Kumara',
                'department' => 'Hyde Park',
                'designation' => 'Customer Relations Officer',
            ],
            [
                'email' => '008665@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008665',
                'name' => 'Mohamed Naseer Mohamed Faizal',
                'department' => 'Hyde Park',
                'designation' => 'Cashier',
            ],
            [
                'email' => '008830@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '008830',
                'name' => 'Tuan Sukurna Mohamed Shuhadh Khan',
                'department' => 'Hyde Park',
                'designation' => 'Team Leader',
            ],
            [
                'email' => '009118@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009118',
                'name' => 'Fathima Zumra Hassim',
                'department' => 'Hyde Park',
                'designation' => 'Customer Relations Officer',
            ],
            [
                'email' => '009426@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009426',
                'name' => 'Siththambalam Niroja',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel-Senior',
            ],
            [
                'email' => '009643@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009643',
                'name' => 'Mohomed Ansar Muhammadu Uzman',
                'department' => 'Hyde Park',
                'designation' => 'Management Trainee 11',
            ],
            [
                'email' => '009644@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009644',
                'name' => 'Muhammadu Mubarak Mohamed Saajith',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel',
            ],
            [
                'email' => '009653@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009653',
                'name' => 'Hene Gedara Nandani Jayalath',
                'department' => 'Hyde Park',
                'designation' => 'Welcome Staff',
            ],
            [
                'email' => '009710@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009710',
                'name' => 'Mohamed Jahangeer Mohamed Ifham',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel-Senior',
            ],
            [
                'email' => '009711@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009711',
                'name' => 'Rengaiya Rajaratnam',
                'department' => 'Hyde Park',
                'designation' => 'Senior Team Leader',
            ],
            [
                'email' => '009740@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009740',
                'name' => 'Siththi Zeenath Burhanudeen',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel',
            ],
            [
                'email' => '009880@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '009880',
                'name' => 'Mohomed Yaseen Mohomed Ijas',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel',
            ],
            [
                'email' => '010045@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010045',
                'name' => 'Subramani Shamila',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel-Trainee',
            ],
            [
                'email' => '010047@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010047',
                'name' => 'Gunasekaran Linduja',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel-Trainee',
            ],
            [
                'email' => '010116@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010116',
                'name' => 'Jeganathan Thayalini',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel-Trainee',
            ],
            [
                'email' => '010117@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010117',
                'name' => 'Mohammad Iqbal Mohammad Ifras',
                'department' => 'Hyde Park',
                'designation' => 'Cashier-Trainee',
            ],
            [
                'email' => '010146@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010146',
                'name' => 'Mohamed Farook Mohamed Fahad',
                'department' => 'Hyde Park',
                'designation' => 'Cashier-Trainee',
            ],
            [
                'email' => '010158@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010158',
                'name' => 'Mohomad Oseer Isham Mohomad',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel',
            ],
            [
                'email' => '010230@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010230',
                'name' => 'Tuan Hassim Zahirsa',
                'department' => 'Hyde Park',
                'designation' => 'Security Personnel',
            ],
            [
                'email' => '010305@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010305',
                'name' => 'Munawwar Mohamad Mimthas',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel-Senior',
            ],
            [
                'email' => '010306@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010306',
                'name' => 'Mogan Nalini',
                'department' => 'Hyde Park',
                'designation' => 'Cashier-Trainee',
            ],
            [
                'email' => '010307@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010307',
                'name' => 'Firdaws Mohomed Ishak',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel-Trainee',
            ],
            [
                'email' => '010308@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010308',
                'name' => 'Hewa Maddumage Madushi Dilhara',
                'department' => 'Hyde Park',
                'designation' => 'Customer Relations Officer',
            ],
            [
                'email' => '010309@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010309',
                'name' => 'Mohamed Ajees Ibraheem',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel-Trainee',
            ],
            [
                'email' => '010399@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010399',
                'name' => 'Mohammadu Siddeek Mohammad Shiyan',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel-Trainee',
            ],
            [
                'email' => '010442@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010442',
                'name' => 'Mohamed Sanoon Nona Nihara Sanoon',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel-Trainee',
            ],
            [
                'email' => '010443@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010443',
                'name' => 'Abdul Kadhar Mohamed Faslan',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel-Trainee',
            ],
            [
                'email' => '010444@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010444',
                'name' => 'Mohommadu Arshad Waleeth Ahamed',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel-Trainee',
            ],
            [
                'email' => '010445@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010445',
                'name' => 'Karuppaiah Karuppaiah Rubani',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel',
            ],
            [
                'email' => '010446@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010446',
                'name' => 'Thiagaraja Piraveena',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel-Senior',
            ],
            [
                'email' => '010455@nolimit.com',
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'emp_no' => '010455',
                'name' => 'Mohammed Macasha Fathima Ashrafa',
                'department' => 'Hyde Park',
                'designation' => 'Sales Personnel-Trainee',
            ],
        ]);
    }
}
