#!/bin/bash

VERSION=""
COMMITMESSAGE="Releasing version $NEW_TAG, Tavis CI will run on this tag"
#get parameters
while getopts v: flag
do
  case "${flag}" in
    v) VERSION=${OPTARG};;
  esac
done

#get highest tag number, and add 1.0.0 if doesn't exist
CURRENT_VERSION=`git describe --abbrev=0 --tags 2>/dev/null`

if [[ $CURRENT_VERSION == '' ]]
then
  CURRENT_VERSION='v0.0.0.0'
fi
echo "Current Version: $CURRENT_VERSION"

CURRENT_VERSION=`echo $CURRENT_VERSION | sed 's/v//g'`
#replace . with space so can split into an array
CURRENT_VERSION_PARTS=(${CURRENT_VERSION//./ })

#get number parts
VNUM1=${CURRENT_VERSION_PARTS[0]}
VNUM2=${CURRENT_VERSION_PARTS[1]}
VNUM3=${CURRENT_VERSION_PARTS[2]}
VNUM4=${CURRENT_VERSION_PARTS[3]}

if [[ $VERSION == 'major' ]]
then
  VNUM1=$((VNUM1+1))
  VNUM2=0
  VNUM3=0
  VNUM4=0
  COMMITMESSAGE="Releasing version $NEW_TAG, Tavis CI will run on this tag"
elif [[ $VERSION == 'minor' ]]
then
  VNUM2=$((VNUM2+1))
  VNUM3=0
  VNUM4=0
  COMMITMESSAGE="Releasing version $NEW_TAG, Tavis CI will run on this tag"
elif [[ $VERSION == 'patch' ]]
then
  VNUM3=$((VNUM3+1))
  VNUM4=0
  COMMITMESSAGE="Releasing version $NEW_TAG, Tavis CI will run on this tag"
elif [[ $VERSION == 'debug' ]]
then
  VNUM4=$((VNUM4+1))
  COMMITMESSAGE="Releasing version $NEW_TAG, Tavis CI will not run on this tag [skip ci]"
else
  echo "No version type (https://semver.org/) or incorrect type specified, try: -v [major, minor, patch, debug]"
  exit 1
fi


#create new tag
NEW_TAG="v$VNUM1.$VNUM2.$VNUM3.$VNUM4"
echo "($VERSION) updating $CURRENT_VERSION to $NEW_TAG"

#get current hash and see if it already has a tag
GIT_COMMIT=`git rev-parse HEAD`
NEEDS_TAG=`git describe --contains $GIT_COMMIT 2>/dev/null`

#only tag if no tag already f
#to publish, need to be logged in to npm, and with clean working directory: `npm login; git stash`
if [ -z "$NEEDS_TAG" ]; then
  git tag -a $NEW_TAG -m "$COMMITMESSAGE"
  echo "Tagged with $NEW_TAG"
  git push --tags
  git push origin master
else
  echo "Already a tag on this commit"
fi

exit 0
